language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - pecl channel-update pecl.php.net
  - yes "" | pecl install yaml
  - composer install
  - vendor/unb-libraries/dockworker/scripts/travis/init.sh

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH
  - vendor/bin/dockworker deployment:logs:check $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: Q3gVQnAXSyyCqJYVjbGR91xwxRPoPvZvInSKhFbBseR5P2fH0GpvuOZUXBXCnRjetlHykJVxD82BkjB863gqOxJTQEzvDX+YSiAVKZRq7Ms27js4xyb9O7GOPWvQtsU0FPPddzzuaeQATd5bJTlIP02+N0kELZv+0+FRp1piSZmYSh4XLfyl9xUsSkyA9NadbA+djlOvxFrSn5Qt+cL1sB/3igAJuU5La3B/JcyR40G5VqJnN3UVMSsajSL6XrSILvvjiTyuFq7OH+RW2vS/Mb7wZY9PhxdNOjuTp35fqB0RdNGSLrLEgonT6Tjo2jTlmto97YGnledaVq9M04xtNybTZdmVwgw6ZRIF7yIxBUEqEBdAxllCIjfMs5Ac8EqgFSorwuQ+Q59hc94/gEm2rpoXPdzsNZaUXpe83o6Yd0kHRgK5AZl3Mx2aimRSViT41xx1yTZRXWGawE1ZGRdPQJB3CJYvrFov61tZlJ7YqO/ik88ZtZCyxIjd8IZkx0Co4gaYad5m9eALM1Qmbdo9hPok2jz4Ie/8TkukjTeXfVNle5qIcCh5tgaT6SG+LJsQRdRZDsxLgP3Khx3lrXLaHZzsVS2QnWGSYTbhED9HoSS6xBx/+ldka7C7UcNZsNHUpfym3JcjpidVsZrBHAGmi3cTv0eNgRbBsYVZ8M+L20Q=
    on_start: always
    on_success: always
