version: '2'

services:
  mysql:
    image: mysql
    command: mysqld --skip-name-resolve
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"

  cogswell.lib.unb.ca:
    build: .
    container_name: cogswell.lib.unb.ca
    expose:
     - "80"
    ports:
      - "3086:80"
    env_file:
      - ./env/drupal.env
    volumes:
      - ./config-yml:/app/configuration
      - ./custom/modules:/app/modules/custom
      - ./custom/themes:/app/themes/custom
      - ./tests/behat.yml:/tmp/drupal_build/behat.yml
      - ./tests/features:/tmp/drupal_build/features

  mysqlimport:
    image: mysql
    expose:
     - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: datadump
    volumes:
      - /Users/cvillami/db_dumps/:/docker-entrypoint-initdb.d
