<?php

/**
 * @file
 * Contains cogswell_migration.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cogswell_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cogswell_migration module.
    case 'help.page.cogswell_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
