features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 0
favicon:
  mimetype: image/png
  path: 'public://favicon.png'
  url: 'http://localhost:3086/sites/default/files/favicon.png'
  use_default: 0
schemas:
  bootstrap: 8000
  cogswell_theme: 8000
